name: Build SunamoParsing

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoParsing
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoParsing/SunamoParsing.csproj

    - name: Build
      run: dotnet build SunamoParsing/SunamoParsing.csproj --configuration Release --no-restore

  test:
    name: Test SunamoParsing.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoParsing.Tests/SunamoParsing.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoParsing.Tests/SunamoParsing.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoParsing.Tests/SunamoParsing.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
